### ISSUE TITLE
Hosting & persistance

### ISSUE THREAD

**Issue by jjg** [bnolan/scenevr#36]
I noticed the hosting & persistence sections of the roadmap (http://www.scenevr.com/roadmap.html) and it coincides with an interest I have in adding the ability to pull scenes from a store that could theoretically be edited from anywhere, including inside a scene itself.

What I had in mind was adding the ability to pull scenes from a storage service I've been working on called JSFS (https://github.com/jjg/jsfs).  It's essentially a REST-based file store with some added cleverness, written in Javascript.

I don't know if it might also meet the needs you have for hosting and persistence, but thought I'd mention it and let you know it was on my list to experiment with loading scenes from JSFS.

**Comment by bnolan** [comment]
Heya @jjg, i've got the hosting service running at http://scenevr.hosting/, it's using a pretty straightforward rails app, drag/drop file uploading and a node script that uses upstart and forever to run the processes. It forwards requests from nginx->node using a lua script that looks up the redis port number for this subdomain. Seems pretty good so far.

**Comment by jjg** [comment]
Looks interesting @bnolan, I'll check it out.
