### ISSUE TITLE
Port to Javascript

### ISSUE THREAD

**Issue by bnolan** [bnolan/scenevr#4]
Currently most of scenevr is in coffeescript, which I'm really happy writing, but this is an open question for people who want to compile all the coffeescript to javascript, commit the javascript, then just do javascript from that point on. It's just up for discussion at the moment, no promise of if / when this will happen.

**Comment by jjg** [comment]
+1 Javascriot

**Comment by bnolan** [comment]
Done, just the specs left to move.
