### ISSUE TITLE
SceneVR is unable to connect to home.scenevr.hosting

### ISSUE THREAD

**Issue by dominictarr** [bnolan/scenevr#49]
I linked this to a friend (who was using chrome 41 on windows) and he got this error.
I was able to connect multiple tabs though (chromium 39 on linux).

**Comment by bnolan** [comment]
It's probably because their ISP has a transparent proxy that blocks
websocket upgrade requests on port 80. I'm moving everything to port 8080
to solve this.

On Thursday, April 2, 2015, Dominic Tarr <notifications@github.com> wrote:

> I linked this to a friend (who was using chrome 41 on windows) and he got
> this error.
> I was able to connect multiple tabs though (chromium 39 on linux).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnolan/scenevr/issues/49>.
>


-- 
Regards,
Ben Nolan

http://bennolan.com/

skype: bennolan
cell: +64 21 770 662

**Comment by dominictarr** [comment]
I understand that https is the best way to ensure you have a good connection, but more expensive...

**Comment by bnolan** [comment]
I want to move everything to SSL. Because the client is served from s3 it'll require jumping through a few hoops.

**Comment by bnolan** [comment]
Fixed in https://github.com/bnolan/scenevr-web/commit/57244b8c0c5d9c2fdf5222bea7c82ca2f1c3381f.

Going to change the protocol docs to recommend people host on port 8080, and change the default websocket port to 8080.

**Comment by dominictarr** [comment]
so should this be fixed on http://client.scenevr.com ?

**Comment by dominictarr** [comment]
I have received confirmation that this is indeed fixed!
