### ISSUE TITLE
Please add sounds

### ISSUE THREAD

**Issue by disasteradio** [bnolan/scenevr#52]
HEY THIS IS AWESOME, and if there was ability to stream mp3 & ogg then I'd love to build something in this! I've actually been looking for a way to do a 3d environment for a new record I'm working on.

**Comment by bnolan** [comment]
I've got some work kicking around for an audio element and can roll it out again! A few questions:

* Should the audio elements be synced between players (so everyone hears the music start at the same time, and if someone joins halfway through a track, their browser will scrub ahead to where the music is playing)

* Is positional audio important, or do you just want to the sound to play at an even volume throughout the scene?

I'd love to work with you on a scene DR! Slowed down [push up](https://soundcloud.com/disasteradio/i-slowed-down-push-up-by-the) is awesome ;)

**Comment by disasteradio** [comment]
what I was imagining was "an album you could walk through", how that is expressed exactly depends on what works exactly. Would a sound within a null (ie invisible) bounding box be simple to implement? or I guess null objects you walk through as a trigger to make one tune take presidence over the rest. 

I think in terms of triggering and sync, a global loop for all players would make the most sense, I mean if they are more-or-less hearing the same position the VR space kinda takes dominance. to enter and leave different zones at different points would make players come back.

**Comment by bnolan** [comment]
Yeah. The audio element is already a null object, you can't see it but it has a position, and the audio is attenuated based on your distance from it. I like the idea of syncing up the playback to all players, so you can experience a track together. I'll dig up the existing audio code and put up a demo. There is a control panel in SceneVR now, so you can turn the volume up / down, which is why I disabled the audio element originally.

**Comment by bnolan** [comment]
Fixed in 7076d95. Added sounds to queenie and snoo in the homeroom. Click them to play. Sounds are played by all players and in sync, but only if all players are present when the sound starts (if you join halfway through a track playing you won't be synced up).
