### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sirkitree** [bnolan/scenevr#6]
Just wondering what your future plans are for this project and areas that you might want help. It's a pretty exciting project to me and though I've been into Janus VR for a little while, this is basically the exact idea of what I thought a more 'modern' project should look like. Huge Kudos.

So in terms of the future, features you want to add, and general direction, I'd love to know what you're thinking so that I can possibly align some goals that I also have.

**Comment by bnolan** [comment]
Put up a roadmap here:

http://www.scenevr.com/roadmap.html
